# Generated by Django 3.2.9 on 2021-12-01 16:06

from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0006_contractabi_abi_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="address",
            field=gnosis.eth.django.models.EthereumAddressV2Field(
                primary_key=True, serialize=False
            ),
        ),
    ]
